# Generated by Django 3.0.10 on 2020-10-25 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custusers', '0002_auto_20201025_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='type',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('API', 'API'), ('WEB', 'WEB')], default='DEFAULT', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('API', 'API'), ('WEB', 'WEB')], default='DEFAULT', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
