# Generated by Django 3.0.10 on 2020-10-25 17:26

import custusers.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custusers', '0003_auto_20201025_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='profile',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=custusers.models.user_profile_dict, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=custusers.models.user_profile_dict, null=True),
        ),
    ]
