# Generated by Django 3.1.8 on 2021-04-09 19:30

import custusers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custusers', '0005_auto_20210409_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='profile',
            field=models.JSONField(default=custusers.models.user_profile_dict, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.JSONField(default=custusers.models.user_profile_dict, null=True),
        ),
    ]
