# Generated by Django 3.0.6 on 2020-05-12 14:36

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertingTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default template', max_length=256)),
                ('action', models.CharField(choices=[('debug', 'Debug'), ('event', 'PatrowlHears event'), ('logfile', 'Logfile'), ('email', 'Email'), ('thehive', 'TheHive alert'), ('twitter', 'Twitter message'), ('slack', 'Slack message'), ('splunk', 'Splunk message')], default='debug', max_length=10)),
                ('canvas', models.CharField(default='n/a', max_length=50)),
            ],
            options={
                'db_table': 'alerting_templates',
            },
        ),
        migrations.CreateModel(
            name='AlertingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New alerting rule', max_length=256)),
                ('target', models.CharField(choices=[('add_vuln', 'New vulnerability'), ('update_vuln', 'Change(s) in vulnerability'), ('add_exploit', 'New exploit'), ('update_exploit', 'Change(s) in exploit')], default='add_vuln', max_length=32)),
                ('action', models.CharField(choices=[('debug', 'Debug'), ('event', 'PatrowlHears event'), ('logfile', 'Logfile'), ('email', 'Email'), ('thehive', 'TheHive alert'), ('twitter', 'Twitter message'), ('slack', 'Slack message'), ('splunk', 'Splunk message')], default='debug', max_length=10)),
                ('conditions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('check_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=64), blank=True, null=True, size=None)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('on_monitored', models.BooleanField(default=False)),
                ('in_bulk', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alerts.AlertingTemplate')),
            ],
            options={
                'db_table': 'alerting_rules',
            },
        ),
    ]
