# Generated by Django 3.1.8 on 2021-04-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertingrule',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
