# Generated by Django 3.0.8 on 2020-07-31 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since_date', models.DateTimeField(null=True)),
                ('to_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('finished', 'Finished'), ('failed', 'Failed')], default='started', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'datasync',
            },
        ),
    ]
