# Generated by Django 3.0.8 on 2020-07-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasync',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
