# Generated by Django 3.0.8 on 2020-08-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_datasync_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasync',
            name='mdl_name',
            field=models.CharField(choices=[('kb_cwe', 'kb_cwe'), ('kb_cpe', 'kb_cpe'), ('kb_cve', 'kb_cve'), ('kb_vendor', 'kb_vendor'), ('kb_product', 'kb_product'), ('kb_product_version', 'kb_product_version'), ('vulns', 'vulns'), ('exploits', 'exploits'), ('threats', 'threats')], default='', max_length=50),
        ),
    ]
