# Generated by Django 3.0.8 on 2020-08-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_datasync_mdl_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasync',
            name='last_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
