# Generated by Django 3.0.8 on 2020-08-03 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_datasync_last_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasync',
            old_name='last_id',
            new_name='from_id',
        ),
    ]
