# Generated by Django 3.0.8 on 2020-08-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200803_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasync',
            name='has_more_updates',
            field=models.BooleanField(default=True),
        ),
    ]
