# Generated by Django 3.0.8 on 2020-08-05 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_datasync_has_more_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSyncJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('finished', 'Finished'), ('failed', 'Failed')], default='started', max_length=20)),
                ('progression', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'datasyncjob',
            },
        ),
        migrations.AddField(
            model_name='datasync',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DataSyncJob'),
        ),
    ]
