# Generated by Django 3.0.10 on 2020-12-23 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200921_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFeedImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(default='')),
                ('hash', models.TextField(default='')),
                ('type', models.CharField(choices=[('vuln', 'Vuln'), ('exploit', 'Exploit'), ('advisory', 'Advisory')], default='vuln', max_length=20)),
                ('object_id', models.BigIntegerField()),
                ('has_error', models.BooleanField(default=False)),
                ('comments', models.TextField(default='')),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'datafeedimport',
            },
        ),
        migrations.AddIndex(
            model_name='datafeedimport',
            index=models.Index(fields=['hash'], name='datafeedimp_hash_5adc2f_idx'),
        ),
        migrations.AddIndex(
            model_name='datafeedimport',
            index=models.Index(fields=['filename'], name='datafeedimp_filenam_6f4e6b_idx'),
        ),
    ]
