# Generated by Django 3.0.10 on 2020-12-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20201223_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafeedimport',
            name='source',
            field=models.TextField(default=''),
        ),
    ]
