# Generated by Django 3.0.6 on 2020-05-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0002_auto_20200520_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploitmetadata',
            name='source',
            field=models.CharField(default='patrowl', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='exploitmetadata',
            name='tlp_level',
            field=models.CharField(choices=[('white', 'White'), ('green', 'Green'), ('amber', 'Amber'), ('red', 'Red'), ('black', 'Black')], default='amber', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalexploitmetadata',
            name='source',
            field=models.CharField(default='patrowl', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalexploitmetadata',
            name='tlp_level',
            field=models.CharField(choices=[('white', 'White'), ('green', 'Green'), ('amber', 'Amber'), ('red', 'Red'), ('black', 'Black')], default='amber', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalorgexploitmetadata',
            name='source',
            field=models.CharField(default='patrowl', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorgexploitmetadata',
            name='tlp_level',
            field=models.CharField(choices=[('white', 'White'), ('green', 'Green'), ('amber', 'Amber'), ('red', 'Red'), ('black', 'Black')], default='amber', max_length=20),
        ),
        migrations.AlterField(
            model_name='orgexploitmetadata',
            name='source',
            field=models.CharField(default='patrowl', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orgexploitmetadata',
            name='tlp_level',
            field=models.CharField(choices=[('white', 'White'), ('green', 'Green'), ('amber', 'Amber'), ('red', 'Red'), ('black', 'Black')], default='amber', max_length=20),
        ),
    ]
