# Generated by Django 3.0.6 on 2020-05-22 18:02

from django.db import migrations, models
import uuid

def create_uuid(apps, schema_editor):
    Vuln = apps.get_model('vulns', 'Vuln')
    for vuln in Vuln.objects.all():
        vuln.uuid = uuid.uuid4()
        vuln.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0003_auto_20200522_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvuln',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        # migrations.AddField(
        #     model_name='vuln',
        #     name='uuid',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        # ),
        migrations.AddField(
            model_name='vuln',
            name='uuid',
            field=models.UUIDField(blank=True, null=True)
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='vuln',
            name='uuid',
            field=models.UUIDField(unique=True)
        ),
    ]
