# Generated by Django 3.0.10 on 2020-10-19 12:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0007_auto_20201019_1201'),
        ('vulns', '0006_auto_20200921_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvuln',
            name='cvss_vector',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvuln',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicalvuln',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvuln',
            name='vulnerable_products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='cvss_vector',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='cwe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cves.CWE'),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='vulnerable_products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), blank=True, null=True, size=None),
        ),
    ]
