# Generated by Django 3.0.10 on 2020-12-21 18:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0013_delete_historicalpackage'),
        ('vulns', '0009_auto_20201211_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvuln',
            name='vulnerable_packages_versions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='vuln',
            name='packages',
            field=models.ManyToManyField(related_name='vulns', to='cves.Package'),
        ),
        migrations.AddField(
            model_name='vuln',
            name='vulnerable_packages_versions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
