# Generated by Django 3.0.10 on 2020-12-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0010_auto_20201221_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvuln',
            name='feedid',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vuln',
            name='feedid',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
