# Generated by Django 3.0.11 on 2021-01-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0012_auto_20201223_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvuln',
            name='assigner',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='assigner',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
