# Generated by Django 3.1.8 on 2021-04-09 19:30

from django.db import migrations, models
import vulns.models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0013_auto_20210112_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploitmetadata',
            name='raw',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalexploitmetadata',
            name='raw',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalorgexploitmetadata',
            name='raw',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalorgthreatmetadata',
            name='raw',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalthreatmetadata',
            name='raw',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalvuln',
            name='access',
            field=models.JSONField(default=vulns.models.access_default_dict),
        ),
        migrations.AlterField(
            model_name='historicalvuln',
            name='cvss3_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalvuln',
            name='cvss_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalvuln',
            name='impact',
            field=models.JSONField(default=vulns.models.impact_default_dict),
        ),
        migrations.AlterField(
            model_name='historicalvuln',
            name='reflinkids',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='historicalvuln',
            name='reflinks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='historicalvuln',
            name='vulnerable_packages_versions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalvuln',
            name='vulnerable_product_versions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='orgexploitmetadata',
            name='raw',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='orgthreatmetadata',
            name='raw',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='threatmetadata',
            name='raw',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='access',
            field=models.JSONField(default=vulns.models.access_default_dict),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='cvss3_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='cvss_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='impact',
            field=models.JSONField(default=vulns.models.impact_default_dict),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='reflinkids',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='reflinks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='vulnerable_packages_versions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='vulnerable_product_versions',
            field=models.JSONField(default=dict),
        ),
    ]
