# Generated by Django 3.1.13 on 2021-12-23 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_field_fix_and_editable'),
        ('vulns', '0014_auto_20210409_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgVulnMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_vulns_metadata', to='organizations.organization')),
                ('vuln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_vulns_metadata', to='vulns.vuln')),
            ],
            options={
                'verbose_name': 'Organization Vulnerability Metadata',
                'verbose_name_plural': 'Organization Vulnerabilities Metadata',
                'db_table': 'org_vulns_metadata',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrgVulnMetadata',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('vuln', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vulns.vuln')),
            ],
            options={
                'verbose_name': 'historical Organization Vulnerability Metadata',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
