# Generated by Django 3.1.13 on 2022-01-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0015_historicalorgvulnmetadata_orgvulnmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorgvulnmetadata',
            name='status',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('fixed', 'Fixed'), ('not_interesting', 'Not Interesting'), ('in_progress', 'In Progress')], default='undefined', max_length=20),
        ),
        migrations.AddField(
            model_name='orgvulnmetadata',
            name='status',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('fixed', 'Fixed'), ('not_interesting', 'Not Interesting'), ('in_progress', 'In Progress')], default='undefined', max_length=20),
        ),
    ]
