# Generated by Django 3.0.2 on 2020-01-13 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitored_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredasset',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('monitoring', 'Monitoring')], default='monitoring', max_length=20),
        ),
        migrations.AlterField(
            model_name='monitoredasset',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredasset',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
