# Generated by Django 3.0.2 on 2020-01-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitored_assets', '0002_auto_20200113_0939'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monitoredasset',
            table='monitored_assets',
        ),
    ]
