# Generated by Django 3.0.2 on 2020-01-13 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitored_assets', '0004_assetmetadata_historicalassetmetadata_historicalmonitoredasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmetadata',
            name='asset',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='monitored_assets.MonitoredAsset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalassetmetadata',
            name='asset',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='monitored_assets.MonitoredAsset'),
        ),
    ]
