# Generated by Django 3.0.8 on 2020-07-29 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0002_auto_20200512_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwe',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='cwe',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
