# Generated by Django 3.0.8 on 2020-07-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0003_auto_20200729_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwe',
            name='cwe_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
