# Generated by Django 3.0.10 on 2020-10-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0005_auto_20201019_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='cvss_vector',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='cwe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cves.CWE'),
        ),
    ]
