# Generated by Django 3.0.10 on 2020-10-19 12:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0006_auto_20201019_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='vulnerable_products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), blank=True, null=True, size=None),
        ),
    ]
