# Generated by Django 3.0.10 on 2020-10-22 18:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0007_auto_20201019_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='versions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), null=True, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='versions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), null=True, size=None),
        ),
    ]
