# Generated by Django 3.0.10 on 2020-11-17 18:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0008_auto_20201022_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwe',
            name='refs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
