# Generated by Django 3.0.10 on 2020-12-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0010_auto_20201211_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='cvss_version',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
