# Generated by Django 3.0.10 on 2020-12-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0012_historicalpackage_package_packagetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPackage',
        ),
    ]
