# Generated by Django 3.1.8 on 2021-04-09 19:30

import cves.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0013_delete_historicalpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='access',
            field=models.JSONField(default=cves.models.access_default_dict),
        ),
        migrations.AlterField(
            model_name='cve',
            name='cvss3_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cve',
            name='cvss_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cve',
            name='impact',
            field=models.JSONField(default=cves.models.impact_default_dict),
        ),
        migrations.AlterField(
            model_name='cve',
            name='references',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cwe',
            name='refs',
            field=models.JSONField(default=dict),
        ),
    ]
