# Generated by Django 3.1.13 on 2023-01-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0014_auto_20210409_1930'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['name'], name='kb_vendor_name_43938a_idx'),
        ),
    ]
