# Generated by Django 3.1.13 on 2023-01-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0015_auto_20230117_1547'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='kb_product_name_ef6a33_idx'),
        ),
    ]
