# Generated by Django 3.1.13 on 2024-02-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0017_auto_20240209_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.TextField(db_index=True, default='-', max_length=250, unique=True),
        ),
    ]
