# Generated by Django 3.1.13 on 2024-02-09 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0018_auto_20240209_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='versions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='versions',
        ),
        migrations.AlterField(
            model_name='productversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pversions', to='cves.product'),
        ),
    ]
