# Generated by Django 3.1.14 on 2024-12-18 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cves", "0019_auto_20240209_1448"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='historicalproduct',
        #     name='versions',
        # ),
        # migrations.AlterField(
        #     model_name="historicalproduct",
        #     name="name",
        #     field=models.TextField(db_index=True, default="-", max_length=250),
        # ),
        migrations.AlterField(
            model_name="productversion",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="cves.product",
            ),
        ),
    ]
