# Generated by Django 3.0.6 on 2020-05-12 14:36

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import vpratings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vulns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.CharField(default='', max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('score_details', django.contrib.postgres.fields.jsonb.JSONField(default=vpratings.models.get_default_scores)),
                ('cvssv2adj', models.FloatField(default=0.0)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('vuln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulns.Vuln')),
            ],
            options={
                'db_table': 'vpratings',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVPRating',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('vector', models.CharField(default='', max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('score_details', django.contrib.postgres.fields.jsonb.JSONField(default=vpratings.models.get_default_scores)),
                ('cvssv2adj', models.FloatField(default=0.0)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vuln', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vulns.Vuln')),
            ],
            options={
                'verbose_name': 'historical vp rating',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
