# Generated by Django 3.0.6 on 2020-05-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200512_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
