# Generated by Django 3.0.6 on 2020-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorgsettings',
            name='enable_daily_email_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalorgsettings',
            name='enable_monthly_email_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalorgsettings',
            name='enable_weekly_email_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='enable_daily_email_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='enable_monthly_email_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='enable_weekly_email_report',
            field=models.BooleanField(default=False),
        ),
    ]
