# Generated by Django 3.0.6 on 2020-05-12 14:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200512_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorgsettings',
            name='alerts_misp',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=users.models.misp_dict),
        ),
        migrations.AddField(
            model_name='historicalorgsettings',
            name='alerts_misp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalorgsettings',
            name='enable_email_alert_new_vuln',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalorgsettings',
            name='enable_email_alert_update_vuln',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='alerts_misp',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=users.models.misp_dict),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='alerts_misp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='enable_email_alert_new_vuln',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='enable_email_alert_update_vuln',
            field=models.BooleanField(default=False),
        ),
    ]
