# Generated by Django 3.0.11 on 2021-01-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0013_delete_historicalpackage'),
        ('users', '0006_auto_20201117_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmonitoringlist',
            name='packages',
            field=models.ManyToManyField(related_name='org_monitoring_list', to='cves.Package'),
        ),
    ]
