# Generated by Django 3.0.12 on 2021-02-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_orgmonitoringlist_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorgsettings',
            name='enable_instant_email_report_cvss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalorgsettings',
            name='enable_instant_email_report_cvss_value',
            field=models.FloatField(default=8.0, null=True),
        ),
        migrations.AddField(
            model_name='historicalorgsettings',
            name='enable_instant_email_report_exploitable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalorgsettings',
            name='enable_instant_email_report_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalorgsettings',
            name='enable_instant_email_report_score_value',
            field=models.FloatField(default=8.0, null=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='enable_instant_email_report_cvss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='enable_instant_email_report_cvss_value',
            field=models.FloatField(default=8.0, null=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='enable_instant_email_report_exploitable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='enable_instant_email_report_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='enable_instant_email_report_score_value',
            field=models.FloatField(default=8.0, null=True),
        ),
    ]
