# Generated by Django 3.0.12 on 2021-02-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210216_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorgsettings',
            name='enable_instant_email_report_score_value',
            field=models.FloatField(default=80, null=True),
        ),
        migrations.AlterField(
            model_name='orgsettings',
            name='enable_instant_email_report_score_value',
            field=models.FloatField(default=80, null=True),
        ),
    ]
