# Generated by Django 3.1.8 on 2021-04-09 19:30

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210216_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorgsettings',
            name='alerts_misp',
            field=models.JSONField(default=users.models.misp_dict),
        ),
        migrations.AlterField(
            model_name='historicalorgsettings',
            name='alerts_slack',
            field=models.JSONField(default=users.models.slack_dict),
        ),
        migrations.AlterField(
            model_name='historicalorgsettings',
            name='alerts_thehive',
            field=models.JSONField(default=users.models.thehive_dict),
        ),
        migrations.AlterField(
            model_name='orgsettings',
            name='alerts_misp',
            field=models.JSONField(default=users.models.misp_dict),
        ),
        migrations.AlterField(
            model_name='orgsettings',
            name='alerts_slack',
            field=models.JSONField(default=users.models.slack_dict),
        ),
        migrations.AlterField(
            model_name='orgsettings',
            name='alerts_thehive',
            field=models.JSONField(default=users.models.thehive_dict),
        ),
    ]
