# Generated by Django 3.1.13 on 2022-04-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210409_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorgsettings',
            name='enable_instant_email_report_cvss3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalorgsettings',
            name='enable_instant_email_report_cvss3_value',
            field=models.FloatField(default=8.0, null=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='enable_instant_email_report_cvss3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='enable_instant_email_report_cvss3_value',
            field=models.FloatField(default=8.0, null=True),
        ),
    ]
